{{-- resources/views/exports/pdf-template.blade.php --}}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{{ $title }}</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 12px;
      margin: 20px;
    }

    .header {
      text-align: center;
      margin-bottom: 20px;
      border-bottom: 2px solid #333;
      padding-bottom: 10px;
    }

    .header h1 {
      margin: 0;
      color: #333;
    }

    .info {
      margin-bottom: 20px;
    }

    .info table {
      width: 100%;
    }

    .info td {
      padding: 3px 0;
    }

    .data-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    .data-table th {
      background-color: #f5f5f5;
      border: 1px solid #ddd;
      padding: 8px;
      text-align: left;
      font-weight: bold;
    }

    .data-table td {
      border: 1px solid #ddd;
      padding: 6px;
      vertical-align: top;
    }

    .data-table tr:nth-child(even) {
      background-color: #f9f9f9;
    }

    .footer {
      margin-top: 30px;
      text-align: center;
      font-size: 10px;
      color: #666;
    }

    .summary {
      margin-top: 20px;
      background-color: #f8f9fa;
      padding: 10px;
      border-radius: 5px;
    }
  </style>
</head>

<body>
  <div class="header">
    <h1>{{ $title }}</h1>
    @if (isset($village['name']))
      <p>{{ $village['name'] }}</p>
    @endif
  </div>

  <div class="info">
    <table>
      <tr>
        <td><strong>Tanggal Export:</strong></td>
        <td>{{ $exported_at->format('d/m/Y H:i:s') }}</td>
        <td><strong>Total Records:</strong></td>
        <td>{{ count($data) }}</td>
      </tr>
      @if (isset($metadata['exported_by']))
        <tr>
          <td><strong>Diekspor oleh:</strong></td>
          <td>{{ $metadata['exported_by'] }}</td>
          <td><strong>Tipe Export:</strong></td>
          <td>{{ $metadata['export_type'] === 'date_range_filtered' ? 'Filter Tanggal' : 'Semua Data' }}</td>
        </tr>
      @endif
      @if (isset($metadata['date_range']) && $metadata['date_range'] !== 'Semua periode')
        <tr>
          <td><strong>Rentang Tanggal:</strong></td>
          <td colspan="3">{{ $metadata['date_range'] }}</td>
        </tr>
      @endif
    </table>
  </div>

  @if (count($data) > 0)
    <table class="data-table">
      <thead>
        <tr>
          @foreach ($columns as $key => $label)
            <th>{{ $label }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach ($data as $row)
          <tr>
            @foreach ($columns as $key => $label)
              <td>{{ $row[$key] ?? '' }}</td>
            @endforeach
          </tr>
        @endforeach
      </tbody>
    </table>

    <div class="summary">
      <strong>Ringkasan:</strong> Total {{ count($data) }} record berhasil diekspor
    </div>
  @else
    <div class="summary">
      <p>Tidak ada data untuk diekspor.</p>
    </div>
  @endif

  <div class="footer">
    <p>Generated by PAMDes Management System - {{ now()->format('d/m/Y H:i:s') }}</p>
  </div>
</body>

</html>
